sudo: required
services:
  - docker

before_install:
  - docker build -t dennislcfx/notifications -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true dennislcfx/notifications npm run test
